name: "Prune Registry"
description: "Will prune old tags from a Docker registry"
author: "Model W"

branding:
    icon: "trash-2"
    color: "orange"

inputs:
    domain:
        description:
            "Domain name of your registry. Prefix with http:// if not HTTPS"
        required: true
    user:
        description: "User name for authentication"
        required: true
        default: ""
    password:
        description: "Password for authentication"
        required: true
        default: ""
    image:
        description: "Image that you are pruning"
        required: true
    regex:
        description: "Regular expression to match the tags you want"
        required: true

outputs: {}

runs:
    using: node20
    main: dist/index.js
